# Generated by Django 3.0.8 on 2021-03-22 01:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/author_pictures/default_pic_author.jpg', upload_to=users.models.profile_pic_path),
        ),
    ]
