# Generated by Django 3.0.8 on 2021-11-01 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movies.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(blank=True, max_length=52, null=True, upload_to=movies.models.thumbnail_path)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=9)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status')),
                ('plot', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('theme', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('acting', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('direction', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('bg_music', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('cinematography', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('production_design', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('pace', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('editing', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('dialogue', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
