# Generated by Django 3.0.8 on 2022-01-07 08:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movies.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=10)),
                ('movie_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=70)),
                ('poster', models.ImageField(max_length=52, upload_to=movies.models.thumbnail_path)),
                ('cover_poster', models.ImageField(blank=True, max_length=52, null=True, upload_to=movies.models.thumbnail_path)),
                ('review', ckeditor_uploader.fields.RichTextUploadingField()),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
