# Generated by Django 3.0.8 on 2021-12-29 12:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='acting',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='bg_music',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='cinematography',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='dialogue',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='editing',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='imdb_id',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='production_design',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='theme',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default='tt10370710', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movierating',
            name='review',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='babal'),
            preserve_default=False,
        ),
    ]
