# Generated by Django 3.0.8 on 2022-01-17 17:48

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='cover_poster',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.thumbnail_path),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='poster',
            field=models.ImageField(upload_to=movies.models.thumbnail_path),
        ),
    ]
