# Generated by Django 3.0.8 on 2022-01-27 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220117_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movierating',
            name='slug',
            field=models.SlugField(),
        ),
    ]
