# Generated by Django 3.0.8 on 2020-07-29 07:13

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail_img', models.ImageField(max_length=52, null=True, upload_to=posts.models.thumbnail_path)),
                ('slug', models.SlugField(max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
                ('created_on', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status')),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
