# Generated by Django 3.0.8 on 2022-01-17 17:48

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200929_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.thumbnail_path),
        ),
    ]
