# Generated by Django 3.0.8 on 2020-07-31 07:59

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200729_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img',
            field=models.ImageField(blank=True, max_length=52, null=True, upload_to=posts.models.thumbnail_path),
        ),
    ]
